import ViewLocation from './ViewLocation';

import './location-mod.css';
import '../../img/1.jpg';
import '../../img/icons/1-s.png';
import '../../img/icons/2-s.png';
import '../../img/icons/3-s.png';
import '../../img/icons/4-s.png';
import '../../img/icons/5-s.png';
import '../../img/icons/6-s.png';
import '../../img/icons/7-s.png';
import '../../img/icons/8-s.png';
import '../../img/icons/11-s.png';
import '../../img/icons/12-s.png';
import '../../img/icons/13-s.png';
import '../../img/icons/14-s.png';
import '../../img/icons/15-s.png';
import '../../img/icons/16-s.png';
import '../../img/icons/17-s.png';
import '../../img/icons/18-s.png';
import '../../img/icons/19-s.png';
import '../../img/icons/20-s.png';
import '../../img/icons/21-s.png';
import '../../img/icons/22-s.png';
import '../../img/icons/23-s.png';
import '../../img/icons/24-s.png';
import '../../img/icons/25-s.png';
import '../../img/icons/26-s.png';
import '../../img/icons/29-s.png';
import '../../img/icons/30-s.png';
import '../../img/icons/31-s.png';
import '../../img/icons/32-s.png';
import '../../img/icons/33-s.png';
import '../../img/icons/34-s.png';
import '../../img/icons/35-s.png';
import '../../img/icons/36-s.png';
import '../../img/icons/37-s.png';
import '../../img/icons/38-s.png';
import '../../img/icons/39-s.png';
import '../../img/icons/40-s.png';
import '../../img/icons/41-s.png';
import '../../img/icons/42-s.png';
import '../../img/icons/43-s.png';
import '../../img/icons/44-s.png';

export default ViewLocation;